/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ShowcaseRouteRouteImport } from './routes/showcase/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShowcaseIndexRouteImport } from './routes/showcase/index'
import { Route as ShowcaseTextFieldRouteImport } from './routes/showcase/text-field'
import { Route as ShowcaseTextRouteImport } from './routes/showcase/text'
import { Route as ShowcaseLinkRouteImport } from './routes/showcase/link'
import { Route as ShowcaseHeadingRouteImport } from './routes/showcase/heading'
import { Route as ShowcaseCardRouteImport } from './routes/showcase/card'
import { Route as ShowcaseButtonRouteImport } from './routes/showcase/button'
import { Route as ShowcaseBadgeRouteImport } from './routes/showcase/badge'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRouteRoute = ShowcaseRouteRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseIndexRoute = ShowcaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShowcaseRouteRoute,
} as any)
const ShowcaseTextFieldRoute = ShowcaseTextFieldRouteImport.update({
  id: '/text-field',
  path: '/text-field',
  getParentRoute: () => ShowcaseRouteRoute,
} as any)
const ShowcaseTextRoute = ShowcaseTextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => ShowcaseRouteRoute,
} as any)
const ShowcaseLinkRoute = ShowcaseLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => ShowcaseRouteRoute,
} as any)
const ShowcaseHeadingRoute = ShowcaseHeadingRouteImport.update({
  id: '/heading',
  path: '/heading',
  getParentRoute: () => ShowcaseRouteRoute,
} as any)
const ShowcaseCardRoute = ShowcaseCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => ShowcaseRouteRoute,
} as any)
const ShowcaseButtonRoute = ShowcaseButtonRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => ShowcaseRouteRoute,
} as any)
const ShowcaseBadgeRoute = ShowcaseBadgeRouteImport.update({
  id: '/badge',
  path: '/badge',
  getParentRoute: () => ShowcaseRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/showcase': typeof ShowcaseRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/showcase/badge': typeof ShowcaseBadgeRoute
  '/showcase/button': typeof ShowcaseButtonRoute
  '/showcase/card': typeof ShowcaseCardRoute
  '/showcase/heading': typeof ShowcaseHeadingRoute
  '/showcase/link': typeof ShowcaseLinkRoute
  '/showcase/text': typeof ShowcaseTextRoute
  '/showcase/text-field': typeof ShowcaseTextFieldRoute
  '/showcase/': typeof ShowcaseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/showcase/badge': typeof ShowcaseBadgeRoute
  '/showcase/button': typeof ShowcaseButtonRoute
  '/showcase/card': typeof ShowcaseCardRoute
  '/showcase/heading': typeof ShowcaseHeadingRoute
  '/showcase/link': typeof ShowcaseLinkRoute
  '/showcase/text': typeof ShowcaseTextRoute
  '/showcase/text-field': typeof ShowcaseTextFieldRoute
  '/showcase': typeof ShowcaseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/showcase': typeof ShowcaseRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/showcase/badge': typeof ShowcaseBadgeRoute
  '/showcase/button': typeof ShowcaseButtonRoute
  '/showcase/card': typeof ShowcaseCardRoute
  '/showcase/heading': typeof ShowcaseHeadingRoute
  '/showcase/link': typeof ShowcaseLinkRoute
  '/showcase/text': typeof ShowcaseTextRoute
  '/showcase/text-field': typeof ShowcaseTextFieldRoute
  '/showcase/': typeof ShowcaseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/showcase'
    | '/about'
    | '/showcase/badge'
    | '/showcase/button'
    | '/showcase/card'
    | '/showcase/heading'
    | '/showcase/link'
    | '/showcase/text'
    | '/showcase/text-field'
    | '/showcase/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/showcase/badge'
    | '/showcase/button'
    | '/showcase/card'
    | '/showcase/heading'
    | '/showcase/link'
    | '/showcase/text'
    | '/showcase/text-field'
    | '/showcase'
  id:
    | '__root__'
    | '/'
    | '/showcase'
    | '/about'
    | '/showcase/badge'
    | '/showcase/button'
    | '/showcase/card'
    | '/showcase/heading'
    | '/showcase/link'
    | '/showcase/text'
    | '/showcase/text-field'
    | '/showcase/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShowcaseRouteRoute: typeof ShowcaseRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/': {
      id: '/showcase/'
      path: '/'
      fullPath: '/showcase/'
      preLoaderRoute: typeof ShowcaseIndexRouteImport
      parentRoute: typeof ShowcaseRouteRoute
    }
    '/showcase/text-field': {
      id: '/showcase/text-field'
      path: '/text-field'
      fullPath: '/showcase/text-field'
      preLoaderRoute: typeof ShowcaseTextFieldRouteImport
      parentRoute: typeof ShowcaseRouteRoute
    }
    '/showcase/text': {
      id: '/showcase/text'
      path: '/text'
      fullPath: '/showcase/text'
      preLoaderRoute: typeof ShowcaseTextRouteImport
      parentRoute: typeof ShowcaseRouteRoute
    }
    '/showcase/link': {
      id: '/showcase/link'
      path: '/link'
      fullPath: '/showcase/link'
      preLoaderRoute: typeof ShowcaseLinkRouteImport
      parentRoute: typeof ShowcaseRouteRoute
    }
    '/showcase/heading': {
      id: '/showcase/heading'
      path: '/heading'
      fullPath: '/showcase/heading'
      preLoaderRoute: typeof ShowcaseHeadingRouteImport
      parentRoute: typeof ShowcaseRouteRoute
    }
    '/showcase/card': {
      id: '/showcase/card'
      path: '/card'
      fullPath: '/showcase/card'
      preLoaderRoute: typeof ShowcaseCardRouteImport
      parentRoute: typeof ShowcaseRouteRoute
    }
    '/showcase/button': {
      id: '/showcase/button'
      path: '/button'
      fullPath: '/showcase/button'
      preLoaderRoute: typeof ShowcaseButtonRouteImport
      parentRoute: typeof ShowcaseRouteRoute
    }
    '/showcase/badge': {
      id: '/showcase/badge'
      path: '/badge'
      fullPath: '/showcase/badge'
      preLoaderRoute: typeof ShowcaseBadgeRouteImport
      parentRoute: typeof ShowcaseRouteRoute
    }
  }
}

interface ShowcaseRouteRouteChildren {
  ShowcaseBadgeRoute: typeof ShowcaseBadgeRoute
  ShowcaseButtonRoute: typeof ShowcaseButtonRoute
  ShowcaseCardRoute: typeof ShowcaseCardRoute
  ShowcaseHeadingRoute: typeof ShowcaseHeadingRoute
  ShowcaseLinkRoute: typeof ShowcaseLinkRoute
  ShowcaseTextRoute: typeof ShowcaseTextRoute
  ShowcaseTextFieldRoute: typeof ShowcaseTextFieldRoute
  ShowcaseIndexRoute: typeof ShowcaseIndexRoute
}

const ShowcaseRouteRouteChildren: ShowcaseRouteRouteChildren = {
  ShowcaseBadgeRoute: ShowcaseBadgeRoute,
  ShowcaseButtonRoute: ShowcaseButtonRoute,
  ShowcaseCardRoute: ShowcaseCardRoute,
  ShowcaseHeadingRoute: ShowcaseHeadingRoute,
  ShowcaseLinkRoute: ShowcaseLinkRoute,
  ShowcaseTextRoute: ShowcaseTextRoute,
  ShowcaseTextFieldRoute: ShowcaseTextFieldRoute,
  ShowcaseIndexRoute: ShowcaseIndexRoute,
}

const ShowcaseRouteRouteWithChildren = ShowcaseRouteRoute._addFileChildren(
  ShowcaseRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShowcaseRouteRoute: ShowcaseRouteRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
